// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"ptv-tui/client/departures"
	"ptv-tui/client/directions"
	"ptv-tui/client/disruptions"
	"ptv-tui/client/fare_estimate"
	"ptv-tui/client/outlets"
	"ptv-tui/client/patterns"
	"ptv-tui/client/route_types"
	"ptv-tui/client/routes"
	"ptv-tui/client/runs"
	"ptv-tui/client/search"
	"ptv-tui/client/stops"
)

// Default ptvclient HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "timetableapi.ptv.vic.gov.au"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new ptvclient HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Ptvclient {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new ptvclient HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Ptvclient {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new ptvclient client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Ptvclient {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Ptvclient)
	cli.Transport = transport
	cli.Departures = departures.New(transport, formats)
	cli.Directions = directions.New(transport, formats)
	cli.Disruptions = disruptions.New(transport, formats)
	cli.FareEstimate = fare_estimate.New(transport, formats)
	cli.Outlets = outlets.New(transport, formats)
	cli.Patterns = patterns.New(transport, formats)
	cli.RouteTypes = route_types.New(transport, formats)
	cli.Routes = routes.New(transport, formats)
	cli.Runs = runs.New(transport, formats)
	cli.Search = search.New(transport, formats)
	cli.Stops = stops.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Ptvclient is a client for ptvclient
type Ptvclient struct {
	Departures departures.ClientService

	Directions directions.ClientService

	Disruptions disruptions.ClientService

	FareEstimate fare_estimate.ClientService

	Outlets outlets.ClientService

	Patterns patterns.ClientService

	RouteTypes route_types.ClientService

	Routes routes.ClientService

	Runs runs.ClientService

	Search search.ClientService

	Stops stops.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Ptvclient) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Departures.SetTransport(transport)
	c.Directions.SetTransport(transport)
	c.Disruptions.SetTransport(transport)
	c.FareEstimate.SetTransport(transport)
	c.Outlets.SetTransport(transport)
	c.Patterns.SetTransport(transport)
	c.RouteTypes.SetTransport(transport)
	c.Routes.SetTransport(transport)
	c.Runs.SetTransport(transport)
	c.Search.SetTransport(transport)
	c.Stops.SetTransport(transport)
}
