// Code generated by go-swagger; DO NOT EDIT.

package patterns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatternsGetPatternByRunParams creates a new PatternsGetPatternByRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatternsGetPatternByRunParams() *PatternsGetPatternByRunParams {
	return &PatternsGetPatternByRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatternsGetPatternByRunParamsWithTimeout creates a new PatternsGetPatternByRunParams object
// with the ability to set a timeout on a request.
func NewPatternsGetPatternByRunParamsWithTimeout(timeout time.Duration) *PatternsGetPatternByRunParams {
	return &PatternsGetPatternByRunParams{
		timeout: timeout,
	}
}

// NewPatternsGetPatternByRunParamsWithContext creates a new PatternsGetPatternByRunParams object
// with the ability to set a context for a request.
func NewPatternsGetPatternByRunParamsWithContext(ctx context.Context) *PatternsGetPatternByRunParams {
	return &PatternsGetPatternByRunParams{
		Context: ctx,
	}
}

// NewPatternsGetPatternByRunParamsWithHTTPClient creates a new PatternsGetPatternByRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatternsGetPatternByRunParamsWithHTTPClient(client *http.Client) *PatternsGetPatternByRunParams {
	return &PatternsGetPatternByRunParams{
		HTTPClient: client,
	}
}

/*
PatternsGetPatternByRunParams contains all the parameters to send to the API endpoint

	for the patterns get pattern by run operation.

	Typically these are written to a http.Request.
*/
type PatternsGetPatternByRunParams struct {

	/* DateUtc.

	   Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)

	   Format: date-time
	*/
	DateUtc *strfmt.DateTime

	/* Devid.

	   Your developer id
	*/
	Devid *string

	/* Expand.

	   List of objects to be returned in full (i.e. expanded) - options include: All, Stop, Route, Run, Direction, Disruption, VehiclePosition, VehicleDescriptor and None. Default is Disruption. Run must be expanded to receive VehiclePosition and VehicleDescriptor information.
	*/
	Expand []int32

	/* IncludeAdvertisedInterchange.

	     Indicates whether data related to interchanges should be included in the response (default = false)
	When set to true, this parameter enables API clients to retrieve additional exchange information (stops, routes, runs, directions and disruptions) in a single call instead of making multiple requests
	*/
	IncludeAdvertisedInterchange *bool

	/* IncludeGeopath.

	   Indicates if geopath data will be returned (default = false)
	*/
	IncludeGeopath *bool

	/* IncludeSkippedStops.

	   Include any skipped stops in a stopping pattern. Defaults to false.
	*/
	IncludeSkippedStops *bool

	/* RouteType.

	   Number identifying transport mode; values returned via RouteTypes API

	   Format: int32
	*/
	RouteType int32

	/* RunRef.

	   The run_ref is the identifier of a run as returned by the departures/* and runs/* endpoints. WARNING, run_id is deprecated. Use run_ref instead.
	*/
	RunRef string

	/* Signature.

	   Authentication signature for request
	*/
	Signature *string

	/* StopID.

	   Filter by stop_id; values returned by Stops API

	   Format: int32
	*/
	StopID *int32

	/* Token.

	   Please ignore
	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patterns get pattern by run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatternsGetPatternByRunParams) WithDefaults() *PatternsGetPatternByRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patterns get pattern by run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatternsGetPatternByRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithTimeout(timeout time.Duration) *PatternsGetPatternByRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithContext(ctx context.Context) *PatternsGetPatternByRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithHTTPClient(client *http.Client) *PatternsGetPatternByRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDateUtc adds the dateUtc to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithDateUtc(dateUtc *strfmt.DateTime) *PatternsGetPatternByRunParams {
	o.SetDateUtc(dateUtc)
	return o
}

// SetDateUtc adds the dateUtc to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetDateUtc(dateUtc *strfmt.DateTime) {
	o.DateUtc = dateUtc
}

// WithDevid adds the devid to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithDevid(devid *string) *PatternsGetPatternByRunParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithExpand adds the expand to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithExpand(expand []int32) *PatternsGetPatternByRunParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetExpand(expand []int32) {
	o.Expand = expand
}

// WithIncludeAdvertisedInterchange adds the includeAdvertisedInterchange to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithIncludeAdvertisedInterchange(includeAdvertisedInterchange *bool) *PatternsGetPatternByRunParams {
	o.SetIncludeAdvertisedInterchange(includeAdvertisedInterchange)
	return o
}

// SetIncludeAdvertisedInterchange adds the includeAdvertisedInterchange to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetIncludeAdvertisedInterchange(includeAdvertisedInterchange *bool) {
	o.IncludeAdvertisedInterchange = includeAdvertisedInterchange
}

// WithIncludeGeopath adds the includeGeopath to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithIncludeGeopath(includeGeopath *bool) *PatternsGetPatternByRunParams {
	o.SetIncludeGeopath(includeGeopath)
	return o
}

// SetIncludeGeopath adds the includeGeopath to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetIncludeGeopath(includeGeopath *bool) {
	o.IncludeGeopath = includeGeopath
}

// WithIncludeSkippedStops adds the includeSkippedStops to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithIncludeSkippedStops(includeSkippedStops *bool) *PatternsGetPatternByRunParams {
	o.SetIncludeSkippedStops(includeSkippedStops)
	return o
}

// SetIncludeSkippedStops adds the includeSkippedStops to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetIncludeSkippedStops(includeSkippedStops *bool) {
	o.IncludeSkippedStops = includeSkippedStops
}

// WithRouteType adds the routeType to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithRouteType(routeType int32) *PatternsGetPatternByRunParams {
	o.SetRouteType(routeType)
	return o
}

// SetRouteType adds the routeType to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetRouteType(routeType int32) {
	o.RouteType = routeType
}

// WithRunRef adds the runRef to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithRunRef(runRef string) *PatternsGetPatternByRunParams {
	o.SetRunRef(runRef)
	return o
}

// SetRunRef adds the runRef to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetRunRef(runRef string) {
	o.RunRef = runRef
}

// WithSignature adds the signature to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithSignature(signature *string) *PatternsGetPatternByRunParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithStopID adds the stopID to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithStopID(stopID *int32) *PatternsGetPatternByRunParams {
	o.SetStopID(stopID)
	return o
}

// SetStopID adds the stopId to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetStopID(stopID *int32) {
	o.StopID = stopID
}

// WithToken adds the token to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) WithToken(token *string) *PatternsGetPatternByRunParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the patterns get pattern by run params
func (o *PatternsGetPatternByRunParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *PatternsGetPatternByRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DateUtc != nil {

		// query param date_utc
		var qrDateUtc strfmt.DateTime

		if o.DateUtc != nil {
			qrDateUtc = *o.DateUtc
		}
		qDateUtc := qrDateUtc.String()
		if qDateUtc != "" {

			if err := r.SetQueryParam("date_utc", qDateUtc); err != nil {
				return err
			}
		}
	}

	if o.Devid != nil {

		// query param devid
		var qrDevid string

		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {

			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}
	}

	if o.Expand != nil {

		// binding items for expand
		joinedExpand := o.bindParamExpand(reg)

		// query array param expand
		if err := r.SetQueryParam("expand", joinedExpand...); err != nil {
			return err
		}
	}

	if o.IncludeAdvertisedInterchange != nil {

		// query param include_advertised_interchange
		var qrIncludeAdvertisedInterchange bool

		if o.IncludeAdvertisedInterchange != nil {
			qrIncludeAdvertisedInterchange = *o.IncludeAdvertisedInterchange
		}
		qIncludeAdvertisedInterchange := swag.FormatBool(qrIncludeAdvertisedInterchange)
		if qIncludeAdvertisedInterchange != "" {

			if err := r.SetQueryParam("include_advertised_interchange", qIncludeAdvertisedInterchange); err != nil {
				return err
			}
		}
	}

	if o.IncludeGeopath != nil {

		// query param include_geopath
		var qrIncludeGeopath bool

		if o.IncludeGeopath != nil {
			qrIncludeGeopath = *o.IncludeGeopath
		}
		qIncludeGeopath := swag.FormatBool(qrIncludeGeopath)
		if qIncludeGeopath != "" {

			if err := r.SetQueryParam("include_geopath", qIncludeGeopath); err != nil {
				return err
			}
		}
	}

	if o.IncludeSkippedStops != nil {

		// query param include_skipped_stops
		var qrIncludeSkippedStops bool

		if o.IncludeSkippedStops != nil {
			qrIncludeSkippedStops = *o.IncludeSkippedStops
		}
		qIncludeSkippedStops := swag.FormatBool(qrIncludeSkippedStops)
		if qIncludeSkippedStops != "" {

			if err := r.SetQueryParam("include_skipped_stops", qIncludeSkippedStops); err != nil {
				return err
			}
		}
	}

	// path param route_type
	if err := r.SetPathParam("route_type", swag.FormatInt32(o.RouteType)); err != nil {
		return err
	}

	// path param run_ref
	if err := r.SetPathParam("run_ref", o.RunRef); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string

		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {

			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}
	}

	if o.StopID != nil {

		// query param stop_id
		var qrStopID int32

		if o.StopID != nil {
			qrStopID = *o.StopID
		}
		qStopID := swag.FormatInt32(qrStopID)
		if qStopID != "" {

			if err := r.SetQueryParam("stop_id", qStopID); err != nil {
				return err
			}
		}
	}

	if o.Token != nil {

		// query param token
		var qrToken string

		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {

			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamPatternsGetPatternByRun binds the parameter expand
func (o *PatternsGetPatternByRunParams) bindParamExpand(formats strfmt.Registry) []string {
	expandIR := o.Expand

	var expandIC []string
	for _, expandIIR := range expandIR { // explode []int32

		expandIIV := swag.FormatInt32(expandIIR) // int32 as string
		expandIC = append(expandIC, expandIIV)
	}

	// items.CollectionFormat: "multi"
	expandIS := swag.JoinByFormat(expandIC, "multi")

	return expandIS
}
