// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ptv-tui/models"
)

// DisruptionsGetDisruptionsByRouteAndStopReader is a Reader for the DisruptionsGetDisruptionsByRouteAndStop structure.
type DisruptionsGetDisruptionsByRouteAndStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisruptionsGetDisruptionsByRouteAndStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDisruptionsGetDisruptionsByRouteAndStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDisruptionsGetDisruptionsByRouteAndStopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDisruptionsGetDisruptionsByRouteAndStopForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}] Disruptions_GetDisruptionsByRouteAndStop", response, response.Code())
	}
}

// NewDisruptionsGetDisruptionsByRouteAndStopOK creates a DisruptionsGetDisruptionsByRouteAndStopOK with default headers values
func NewDisruptionsGetDisruptionsByRouteAndStopOK() *DisruptionsGetDisruptionsByRouteAndStopOK {
	return &DisruptionsGetDisruptionsByRouteAndStopOK{}
}

/*
DisruptionsGetDisruptionsByRouteAndStopOK describes a response with status code 200, with default header values.

All disruption information (if any exists) for the specified route and stop.
*/
type DisruptionsGetDisruptionsByRouteAndStopOK struct {
	Payload *models.V3DisruptionsResponse
}

// IsSuccess returns true when this disruptions get disruptions by route and stop o k response has a 2xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this disruptions get disruptions by route and stop o k response has a 3xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this disruptions get disruptions by route and stop o k response has a 4xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this disruptions get disruptions by route and stop o k response has a 5xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) IsServerError() bool {
	return false
}

// IsCode returns true when this disruptions get disruptions by route and stop o k response a status code equal to that given
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the disruptions get disruptions by route and stop o k response
func (o *DisruptionsGetDisruptionsByRouteAndStopOK) Code() int {
	return 200
}

func (o *DisruptionsGetDisruptionsByRouteAndStopOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopOK %s", 200, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopOK %s", 200, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopOK) GetPayload() *models.V3DisruptionsResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByRouteAndStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3DisruptionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetDisruptionsByRouteAndStopBadRequest creates a DisruptionsGetDisruptionsByRouteAndStopBadRequest with default headers values
func NewDisruptionsGetDisruptionsByRouteAndStopBadRequest() *DisruptionsGetDisruptionsByRouteAndStopBadRequest {
	return &DisruptionsGetDisruptionsByRouteAndStopBadRequest{}
}

/*
DisruptionsGetDisruptionsByRouteAndStopBadRequest describes a response with status code 400, with default header values.

Invalid Request
*/
type DisruptionsGetDisruptionsByRouteAndStopBadRequest struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this disruptions get disruptions by route and stop bad request response has a 2xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this disruptions get disruptions by route and stop bad request response has a 3xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this disruptions get disruptions by route and stop bad request response has a 4xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this disruptions get disruptions by route and stop bad request response has a 5xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this disruptions get disruptions by route and stop bad request response a status code equal to that given
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the disruptions get disruptions by route and stop bad request response
func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) Code() int {
	return 400
}

func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopBadRequest %s", 400, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopBadRequest %s", 400, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByRouteAndStopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetDisruptionsByRouteAndStopForbidden creates a DisruptionsGetDisruptionsByRouteAndStopForbidden with default headers values
func NewDisruptionsGetDisruptionsByRouteAndStopForbidden() *DisruptionsGetDisruptionsByRouteAndStopForbidden {
	return &DisruptionsGetDisruptionsByRouteAndStopForbidden{}
}

/*
DisruptionsGetDisruptionsByRouteAndStopForbidden describes a response with status code 403, with default header values.

Access Denied
*/
type DisruptionsGetDisruptionsByRouteAndStopForbidden struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this disruptions get disruptions by route and stop forbidden response has a 2xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this disruptions get disruptions by route and stop forbidden response has a 3xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this disruptions get disruptions by route and stop forbidden response has a 4xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this disruptions get disruptions by route and stop forbidden response has a 5xx status code
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this disruptions get disruptions by route and stop forbidden response a status code equal to that given
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the disruptions get disruptions by route and stop forbidden response
func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) Code() int {
	return 403
}

func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopForbidden %s", 403, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/disruptions/route/{route_id}/stop/{stop_id}][%d] disruptionsGetDisruptionsByRouteAndStopForbidden %s", 403, payload)
}

func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByRouteAndStopForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
