// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new disruptions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new disruptions API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new disruptions API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for disruptions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextHTML sets the Accept header to "text/html".
func WithAcceptTextHTML(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/html"}
}

// WithAcceptTextJSON sets the Accept header to "text/json".
func WithAcceptTextJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/json"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	DisruptionsGetAllDisruptions(params *DisruptionsGetAllDisruptionsParams, opts ...ClientOption) (*DisruptionsGetAllDisruptionsOK, error)

	DisruptionsGetDisruptionByID(params *DisruptionsGetDisruptionByIDParams, opts ...ClientOption) (*DisruptionsGetDisruptionByIDOK, error)

	DisruptionsGetDisruptionModes(params *DisruptionsGetDisruptionModesParams, opts ...ClientOption) (*DisruptionsGetDisruptionModesOK, error)

	DisruptionsGetDisruptionsByRoute(params *DisruptionsGetDisruptionsByRouteParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByRouteOK, error)

	DisruptionsGetDisruptionsByRouteAndStop(params *DisruptionsGetDisruptionsByRouteAndStopParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByRouteAndStopOK, error)

	DisruptionsGetDisruptionsByStop(params *DisruptionsGetDisruptionsByStopParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByStopOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DisruptionsGetAllDisruptions views all disruptions for all route types
*/
func (a *Client) DisruptionsGetAllDisruptions(params *DisruptionsGetAllDisruptionsParams, opts ...ClientOption) (*DisruptionsGetAllDisruptionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetAllDisruptionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetAllDisruptions",
		Method:             "GET",
		PathPattern:        "/v3/disruptions",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetAllDisruptionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetAllDisruptionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetAllDisruptions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DisruptionsGetDisruptionByID views a specific disruption
*/
func (a *Client) DisruptionsGetDisruptionByID(params *DisruptionsGetDisruptionByIDParams, opts ...ClientOption) (*DisruptionsGetDisruptionByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetDisruptionByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetDisruptionById",
		Method:             "GET",
		PathPattern:        "/v3/disruptions/{disruption_id}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetDisruptionByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetDisruptionByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetDisruptionById: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DisruptionsGetDisruptionModes gets all disruption modes
*/
func (a *Client) DisruptionsGetDisruptionModes(params *DisruptionsGetDisruptionModesParams, opts ...ClientOption) (*DisruptionsGetDisruptionModesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetDisruptionModesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetDisruptionModes",
		Method:             "GET",
		PathPattern:        "/v3/disruptions/modes",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetDisruptionModesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetDisruptionModesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetDisruptionModes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DisruptionsGetDisruptionsByRoute views all disruptions for a particular route
*/
func (a *Client) DisruptionsGetDisruptionsByRoute(params *DisruptionsGetDisruptionsByRouteParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByRouteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetDisruptionsByRouteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetDisruptionsByRoute",
		Method:             "GET",
		PathPattern:        "/v3/disruptions/route/{route_id}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetDisruptionsByRouteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetDisruptionsByRouteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetDisruptionsByRoute: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DisruptionsGetDisruptionsByRouteAndStop views all disruptions for a particular route and stop
*/
func (a *Client) DisruptionsGetDisruptionsByRouteAndStop(params *DisruptionsGetDisruptionsByRouteAndStopParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByRouteAndStopOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetDisruptionsByRouteAndStopParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetDisruptionsByRouteAndStop",
		Method:             "GET",
		PathPattern:        "/v3/disruptions/route/{route_id}/stop/{stop_id}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetDisruptionsByRouteAndStopReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetDisruptionsByRouteAndStopOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetDisruptionsByRouteAndStop: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DisruptionsGetDisruptionsByStop views all disruptions for a particular stop
*/
func (a *Client) DisruptionsGetDisruptionsByStop(params *DisruptionsGetDisruptionsByStopParams, opts ...ClientOption) (*DisruptionsGetDisruptionsByStopOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDisruptionsGetDisruptionsByStopParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Disruptions_GetDisruptionsByStop",
		Method:             "GET",
		PathPattern:        "/v3/disruptions/stop/{stop_id}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisruptionsGetDisruptionsByStopReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DisruptionsGetDisruptionsByStopOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Disruptions_GetDisruptionsByStop: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
