// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ptv-tui/models"
)

// SearchSearchReader is a Reader for the SearchSearch structure.
type SearchSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchSearchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSearchSearchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v3/search/{search_term}] Search_Search", response, response.Code())
	}
}

// NewSearchSearchOK creates a SearchSearchOK with default headers values
func NewSearchSearchOK() *SearchSearchOK {
	return &SearchSearchOK{}
}

/*
SearchSearchOK describes a response with status code 200, with default header values.

Stops, routes and myki ticket outlets that contain the search term (note: stops and routes are ordered by route_type by default).
*/
type SearchSearchOK struct {
	Payload *models.V3SearchResult
}

// IsSuccess returns true when this search search o k response has a 2xx status code
func (o *SearchSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search search o k response has a 3xx status code
func (o *SearchSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search search o k response has a 4xx status code
func (o *SearchSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search search o k response has a 5xx status code
func (o *SearchSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search search o k response a status code equal to that given
func (o *SearchSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search search o k response
func (o *SearchSearchOK) Code() int {
	return 200
}

func (o *SearchSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchOK %s", 200, payload)
}

func (o *SearchSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchOK %s", 200, payload)
}

func (o *SearchSearchOK) GetPayload() *models.V3SearchResult {
	return o.Payload
}

func (o *SearchSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3SearchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchSearchBadRequest creates a SearchSearchBadRequest with default headers values
func NewSearchSearchBadRequest() *SearchSearchBadRequest {
	return &SearchSearchBadRequest{}
}

/*
SearchSearchBadRequest describes a response with status code 400, with default header values.

Invalid Request
*/
type SearchSearchBadRequest struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this search search bad request response has a 2xx status code
func (o *SearchSearchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search search bad request response has a 3xx status code
func (o *SearchSearchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search search bad request response has a 4xx status code
func (o *SearchSearchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this search search bad request response has a 5xx status code
func (o *SearchSearchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this search search bad request response a status code equal to that given
func (o *SearchSearchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the search search bad request response
func (o *SearchSearchBadRequest) Code() int {
	return 400
}

func (o *SearchSearchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchBadRequest %s", 400, payload)
}

func (o *SearchSearchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchBadRequest %s", 400, payload)
}

func (o *SearchSearchBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *SearchSearchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchSearchForbidden creates a SearchSearchForbidden with default headers values
func NewSearchSearchForbidden() *SearchSearchForbidden {
	return &SearchSearchForbidden{}
}

/*
SearchSearchForbidden describes a response with status code 403, with default header values.

Access Denied
*/
type SearchSearchForbidden struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this search search forbidden response has a 2xx status code
func (o *SearchSearchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search search forbidden response has a 3xx status code
func (o *SearchSearchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search search forbidden response has a 4xx status code
func (o *SearchSearchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this search search forbidden response has a 5xx status code
func (o *SearchSearchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this search search forbidden response a status code equal to that given
func (o *SearchSearchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the search search forbidden response
func (o *SearchSearchForbidden) Code() int {
	return 403
}

func (o *SearchSearchForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchForbidden %s", 403, payload)
}

func (o *SearchSearchForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/search/{search_term}][%d] searchSearchForbidden %s", 403, payload)
}

func (o *SearchSearchForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *SearchSearchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
