// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRunsForRunParams creates a new RunsForRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunsForRunParams() *RunsForRunParams {
	return &RunsForRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunsForRunParamsWithTimeout creates a new RunsForRunParams object
// with the ability to set a timeout on a request.
func NewRunsForRunParamsWithTimeout(timeout time.Duration) *RunsForRunParams {
	return &RunsForRunParams{
		timeout: timeout,
	}
}

// NewRunsForRunParamsWithContext creates a new RunsForRunParams object
// with the ability to set a context for a request.
func NewRunsForRunParamsWithContext(ctx context.Context) *RunsForRunParams {
	return &RunsForRunParams{
		Context: ctx,
	}
}

// NewRunsForRunParamsWithHTTPClient creates a new RunsForRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunsForRunParamsWithHTTPClient(client *http.Client) *RunsForRunParams {
	return &RunsForRunParams{
		HTTPClient: client,
	}
}

/*
RunsForRunParams contains all the parameters to send to the API endpoint

	for the runs for run operation.

	Typically these are written to a http.Request.
*/
type RunsForRunParams struct {

	/* DateUtc.

	   Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)

	   Format: date-time
	*/
	DateUtc *strfmt.DateTime

	/* Devid.

	   Your developer id
	*/
	Devid *string

	/* Expand.

	   List of objects to be returned in full (i.e. expanded) - options include: All, VehiclePosition, VehicleDescriptor, or None. Default is None.
	*/
	Expand []int32

	/* IncludeAdvertisedInterchange.

	     Indicates whether data related to interchanges should be included in the response (default = false).
	When set to true, this parameter enables API clients to retrieve additional exchange information (stops, routes, runs, directions and disruptions) in a single call instead of making multiple requests
	*/
	IncludeAdvertisedInterchange *bool

	/* IncludeGeopath.

	   Indicates if geopath data will be returned (default = false)
	*/
	IncludeGeopath *bool

	/* RunRef.

	   The run_ref is the identifier of a run as returned by the departures/* and runs/* endpoints. WARNING, run_id is deprecated. Use run_ref instead.
	*/
	RunRef string

	/* Signature.

	   Authentication signature for request
	*/
	Signature *string

	/* Token.

	   Please ignore
	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the runs for run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunsForRunParams) WithDefaults() *RunsForRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the runs for run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunsForRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the runs for run params
func (o *RunsForRunParams) WithTimeout(timeout time.Duration) *RunsForRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs for run params
func (o *RunsForRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs for run params
func (o *RunsForRunParams) WithContext(ctx context.Context) *RunsForRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs for run params
func (o *RunsForRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs for run params
func (o *RunsForRunParams) WithHTTPClient(client *http.Client) *RunsForRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs for run params
func (o *RunsForRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDateUtc adds the dateUtc to the runs for run params
func (o *RunsForRunParams) WithDateUtc(dateUtc *strfmt.DateTime) *RunsForRunParams {
	o.SetDateUtc(dateUtc)
	return o
}

// SetDateUtc adds the dateUtc to the runs for run params
func (o *RunsForRunParams) SetDateUtc(dateUtc *strfmt.DateTime) {
	o.DateUtc = dateUtc
}

// WithDevid adds the devid to the runs for run params
func (o *RunsForRunParams) WithDevid(devid *string) *RunsForRunParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the runs for run params
func (o *RunsForRunParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithExpand adds the expand to the runs for run params
func (o *RunsForRunParams) WithExpand(expand []int32) *RunsForRunParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the runs for run params
func (o *RunsForRunParams) SetExpand(expand []int32) {
	o.Expand = expand
}

// WithIncludeAdvertisedInterchange adds the includeAdvertisedInterchange to the runs for run params
func (o *RunsForRunParams) WithIncludeAdvertisedInterchange(includeAdvertisedInterchange *bool) *RunsForRunParams {
	o.SetIncludeAdvertisedInterchange(includeAdvertisedInterchange)
	return o
}

// SetIncludeAdvertisedInterchange adds the includeAdvertisedInterchange to the runs for run params
func (o *RunsForRunParams) SetIncludeAdvertisedInterchange(includeAdvertisedInterchange *bool) {
	o.IncludeAdvertisedInterchange = includeAdvertisedInterchange
}

// WithIncludeGeopath adds the includeGeopath to the runs for run params
func (o *RunsForRunParams) WithIncludeGeopath(includeGeopath *bool) *RunsForRunParams {
	o.SetIncludeGeopath(includeGeopath)
	return o
}

// SetIncludeGeopath adds the includeGeopath to the runs for run params
func (o *RunsForRunParams) SetIncludeGeopath(includeGeopath *bool) {
	o.IncludeGeopath = includeGeopath
}

// WithRunRef adds the runRef to the runs for run params
func (o *RunsForRunParams) WithRunRef(runRef string) *RunsForRunParams {
	o.SetRunRef(runRef)
	return o
}

// SetRunRef adds the runRef to the runs for run params
func (o *RunsForRunParams) SetRunRef(runRef string) {
	o.RunRef = runRef
}

// WithSignature adds the signature to the runs for run params
func (o *RunsForRunParams) WithSignature(signature *string) *RunsForRunParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the runs for run params
func (o *RunsForRunParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the runs for run params
func (o *RunsForRunParams) WithToken(token *string) *RunsForRunParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the runs for run params
func (o *RunsForRunParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RunsForRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DateUtc != nil {

		// query param date_utc
		var qrDateUtc strfmt.DateTime

		if o.DateUtc != nil {
			qrDateUtc = *o.DateUtc
		}
		qDateUtc := qrDateUtc.String()
		if qDateUtc != "" {

			if err := r.SetQueryParam("date_utc", qDateUtc); err != nil {
				return err
			}
		}
	}

	if o.Devid != nil {

		// query param devid
		var qrDevid string

		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {

			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}
	}

	if o.Expand != nil {

		// binding items for expand
		joinedExpand := o.bindParamExpand(reg)

		// query array param expand
		if err := r.SetQueryParam("expand", joinedExpand...); err != nil {
			return err
		}
	}

	if o.IncludeAdvertisedInterchange != nil {

		// query param include_advertised_interchange
		var qrIncludeAdvertisedInterchange bool

		if o.IncludeAdvertisedInterchange != nil {
			qrIncludeAdvertisedInterchange = *o.IncludeAdvertisedInterchange
		}
		qIncludeAdvertisedInterchange := swag.FormatBool(qrIncludeAdvertisedInterchange)
		if qIncludeAdvertisedInterchange != "" {

			if err := r.SetQueryParam("include_advertised_interchange", qIncludeAdvertisedInterchange); err != nil {
				return err
			}
		}
	}

	if o.IncludeGeopath != nil {

		// query param include_geopath
		var qrIncludeGeopath bool

		if o.IncludeGeopath != nil {
			qrIncludeGeopath = *o.IncludeGeopath
		}
		qIncludeGeopath := swag.FormatBool(qrIncludeGeopath)
		if qIncludeGeopath != "" {

			if err := r.SetQueryParam("include_geopath", qIncludeGeopath); err != nil {
				return err
			}
		}
	}

	// path param run_ref
	if err := r.SetPathParam("run_ref", o.RunRef); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string

		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {

			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}
	}

	if o.Token != nil {

		// query param token
		var qrToken string

		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {

			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamRunsForRun binds the parameter expand
func (o *RunsForRunParams) bindParamExpand(formats strfmt.Registry) []string {
	expandIR := o.Expand

	var expandIC []string
	for _, expandIIR := range expandIR { // explode []int32

		expandIIV := swag.FormatInt32(expandIIR) // int32 as string
		expandIC = append(expandIC, expandIIV)
	}

	// items.CollectionFormat: "multi"
	expandIS := swag.JoinByFormat(expandIC, "multi")

	return expandIS
}
