// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRunsForRunAndRouteTypeParams creates a new RunsForRunAndRouteTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunsForRunAndRouteTypeParams() *RunsForRunAndRouteTypeParams {
	return &RunsForRunAndRouteTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunsForRunAndRouteTypeParamsWithTimeout creates a new RunsForRunAndRouteTypeParams object
// with the ability to set a timeout on a request.
func NewRunsForRunAndRouteTypeParamsWithTimeout(timeout time.Duration) *RunsForRunAndRouteTypeParams {
	return &RunsForRunAndRouteTypeParams{
		timeout: timeout,
	}
}

// NewRunsForRunAndRouteTypeParamsWithContext creates a new RunsForRunAndRouteTypeParams object
// with the ability to set a context for a request.
func NewRunsForRunAndRouteTypeParamsWithContext(ctx context.Context) *RunsForRunAndRouteTypeParams {
	return &RunsForRunAndRouteTypeParams{
		Context: ctx,
	}
}

// NewRunsForRunAndRouteTypeParamsWithHTTPClient creates a new RunsForRunAndRouteTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunsForRunAndRouteTypeParamsWithHTTPClient(client *http.Client) *RunsForRunAndRouteTypeParams {
	return &RunsForRunAndRouteTypeParams{
		HTTPClient: client,
	}
}

/*
RunsForRunAndRouteTypeParams contains all the parameters to send to the API endpoint

	for the runs for run and route type operation.

	Typically these are written to a http.Request.
*/
type RunsForRunAndRouteTypeParams struct {

	/* DateUtc.

	   Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)

	   Format: date-time
	*/
	DateUtc *strfmt.DateTime

	/* Devid.

	   Your developer id
	*/
	Devid *string

	/* Expand.

	   List of objects to be returned in full (i.e. expanded) - options include: All, VehiclePosition, VehicleDescriptor, or None. Default is None.
	*/
	Expand []int32

	/* IncludeGeopath.

	   Indicates if geopath data will be returned (default = false)
	*/
	IncludeGeopath *bool

	/* RouteType.

	   Number identifying transport mode; values returned via RouteTypes API

	   Format: int32
	*/
	RouteType int32

	/* RunRef.

	   The run_ref is the identifier of a run as returned by the departures/* and runs/* endpoints. WARNING, run_id is deprecated. Use run_ref instead.
	*/
	RunRef string

	/* Signature.

	   Authentication signature for request
	*/
	Signature *string

	/* Token.

	   Please ignore
	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the runs for run and route type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunsForRunAndRouteTypeParams) WithDefaults() *RunsForRunAndRouteTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the runs for run and route type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunsForRunAndRouteTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithTimeout(timeout time.Duration) *RunsForRunAndRouteTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithContext(ctx context.Context) *RunsForRunAndRouteTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithHTTPClient(client *http.Client) *RunsForRunAndRouteTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDateUtc adds the dateUtc to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithDateUtc(dateUtc *strfmt.DateTime) *RunsForRunAndRouteTypeParams {
	o.SetDateUtc(dateUtc)
	return o
}

// SetDateUtc adds the dateUtc to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetDateUtc(dateUtc *strfmt.DateTime) {
	o.DateUtc = dateUtc
}

// WithDevid adds the devid to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithDevid(devid *string) *RunsForRunAndRouteTypeParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithExpand adds the expand to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithExpand(expand []int32) *RunsForRunAndRouteTypeParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetExpand(expand []int32) {
	o.Expand = expand
}

// WithIncludeGeopath adds the includeGeopath to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithIncludeGeopath(includeGeopath *bool) *RunsForRunAndRouteTypeParams {
	o.SetIncludeGeopath(includeGeopath)
	return o
}

// SetIncludeGeopath adds the includeGeopath to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetIncludeGeopath(includeGeopath *bool) {
	o.IncludeGeopath = includeGeopath
}

// WithRouteType adds the routeType to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithRouteType(routeType int32) *RunsForRunAndRouteTypeParams {
	o.SetRouteType(routeType)
	return o
}

// SetRouteType adds the routeType to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetRouteType(routeType int32) {
	o.RouteType = routeType
}

// WithRunRef adds the runRef to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithRunRef(runRef string) *RunsForRunAndRouteTypeParams {
	o.SetRunRef(runRef)
	return o
}

// SetRunRef adds the runRef to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetRunRef(runRef string) {
	o.RunRef = runRef
}

// WithSignature adds the signature to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithSignature(signature *string) *RunsForRunAndRouteTypeParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithToken(token *string) *RunsForRunAndRouteTypeParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RunsForRunAndRouteTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DateUtc != nil {

		// query param date_utc
		var qrDateUtc strfmt.DateTime

		if o.DateUtc != nil {
			qrDateUtc = *o.DateUtc
		}
		qDateUtc := qrDateUtc.String()
		if qDateUtc != "" {

			if err := r.SetQueryParam("date_utc", qDateUtc); err != nil {
				return err
			}
		}
	}

	if o.Devid != nil {

		// query param devid
		var qrDevid string

		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {

			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}
	}

	if o.Expand != nil {

		// binding items for expand
		joinedExpand := o.bindParamExpand(reg)

		// query array param expand
		if err := r.SetQueryParam("expand", joinedExpand...); err != nil {
			return err
		}
	}

	if o.IncludeGeopath != nil {

		// query param include_geopath
		var qrIncludeGeopath bool

		if o.IncludeGeopath != nil {
			qrIncludeGeopath = *o.IncludeGeopath
		}
		qIncludeGeopath := swag.FormatBool(qrIncludeGeopath)
		if qIncludeGeopath != "" {

			if err := r.SetQueryParam("include_geopath", qIncludeGeopath); err != nil {
				return err
			}
		}
	}

	// path param route_type
	if err := r.SetPathParam("route_type", swag.FormatInt32(o.RouteType)); err != nil {
		return err
	}

	// path param run_ref
	if err := r.SetPathParam("run_ref", o.RunRef); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string

		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {

			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}
	}

	if o.Token != nil {

		// query param token
		var qrToken string

		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {

			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamRunsForRunAndRouteType binds the parameter expand
func (o *RunsForRunAndRouteTypeParams) bindParamExpand(formats strfmt.Registry) []string {
	expandIR := o.Expand

	var expandIC []string
	for _, expandIIR := range expandIR { // explode []int32

		expandIIV := swag.FormatInt32(expandIIR) // int32 as string
		expandIC = append(expandIC, expandIIV)
	}

	// items.CollectionFormat: "multi"
	expandIS := swag.JoinByFormat(expandIC, "multi")

	return expandIS
}
