// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ptv-tui/models"
)

// RunsForRunAndRouteTypeReader is a Reader for the RunsForRunAndRouteType structure.
type RunsForRunAndRouteTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunsForRunAndRouteTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRunsForRunAndRouteTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRunsForRunAndRouteTypeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRunsForRunAndRouteTypeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v3/runs/{run_ref}/route_type/{route_type}] Runs_ForRunAndRouteType", response, response.Code())
	}
}

// NewRunsForRunAndRouteTypeOK creates a RunsForRunAndRouteTypeOK with default headers values
func NewRunsForRunAndRouteTypeOK() *RunsForRunAndRouteTypeOK {
	return &RunsForRunAndRouteTypeOK{}
}

/*
RunsForRunAndRouteTypeOK describes a response with status code 200, with default header values.

The trip/service run details for the run_ref and route type specified.
*/
type RunsForRunAndRouteTypeOK struct {
	Payload *models.V3RunResponse
}

// IsSuccess returns true when this runs for run and route type o k response has a 2xx status code
func (o *RunsForRunAndRouteTypeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this runs for run and route type o k response has a 3xx status code
func (o *RunsForRunAndRouteTypeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runs for run and route type o k response has a 4xx status code
func (o *RunsForRunAndRouteTypeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this runs for run and route type o k response has a 5xx status code
func (o *RunsForRunAndRouteTypeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this runs for run and route type o k response a status code equal to that given
func (o *RunsForRunAndRouteTypeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the runs for run and route type o k response
func (o *RunsForRunAndRouteTypeOK) Code() int {
	return 200
}

func (o *RunsForRunAndRouteTypeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeOK %s", 200, payload)
}

func (o *RunsForRunAndRouteTypeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeOK %s", 200, payload)
}

func (o *RunsForRunAndRouteTypeOK) GetPayload() *models.V3RunResponse {
	return o.Payload
}

func (o *RunsForRunAndRouteTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3RunResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsForRunAndRouteTypeBadRequest creates a RunsForRunAndRouteTypeBadRequest with default headers values
func NewRunsForRunAndRouteTypeBadRequest() *RunsForRunAndRouteTypeBadRequest {
	return &RunsForRunAndRouteTypeBadRequest{}
}

/*
RunsForRunAndRouteTypeBadRequest describes a response with status code 400, with default header values.

Invalid Request
*/
type RunsForRunAndRouteTypeBadRequest struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this runs for run and route type bad request response has a 2xx status code
func (o *RunsForRunAndRouteTypeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this runs for run and route type bad request response has a 3xx status code
func (o *RunsForRunAndRouteTypeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runs for run and route type bad request response has a 4xx status code
func (o *RunsForRunAndRouteTypeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this runs for run and route type bad request response has a 5xx status code
func (o *RunsForRunAndRouteTypeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this runs for run and route type bad request response a status code equal to that given
func (o *RunsForRunAndRouteTypeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the runs for run and route type bad request response
func (o *RunsForRunAndRouteTypeBadRequest) Code() int {
	return 400
}

func (o *RunsForRunAndRouteTypeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeBadRequest %s", 400, payload)
}

func (o *RunsForRunAndRouteTypeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeBadRequest %s", 400, payload)
}

func (o *RunsForRunAndRouteTypeBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RunsForRunAndRouteTypeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsForRunAndRouteTypeForbidden creates a RunsForRunAndRouteTypeForbidden with default headers values
func NewRunsForRunAndRouteTypeForbidden() *RunsForRunAndRouteTypeForbidden {
	return &RunsForRunAndRouteTypeForbidden{}
}

/*
RunsForRunAndRouteTypeForbidden describes a response with status code 403, with default header values.

Access Denied
*/
type RunsForRunAndRouteTypeForbidden struct {
	Payload *models.V3ErrorResponse
}

// IsSuccess returns true when this runs for run and route type forbidden response has a 2xx status code
func (o *RunsForRunAndRouteTypeForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this runs for run and route type forbidden response has a 3xx status code
func (o *RunsForRunAndRouteTypeForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runs for run and route type forbidden response has a 4xx status code
func (o *RunsForRunAndRouteTypeForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this runs for run and route type forbidden response has a 5xx status code
func (o *RunsForRunAndRouteTypeForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this runs for run and route type forbidden response a status code equal to that given
func (o *RunsForRunAndRouteTypeForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the runs for run and route type forbidden response
func (o *RunsForRunAndRouteTypeForbidden) Code() int {
	return 403
}

func (o *RunsForRunAndRouteTypeForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeForbidden %s", 403, payload)
}

func (o *RunsForRunAndRouteTypeForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v3/runs/{run_ref}/route_type/{route_type}][%d] runsForRunAndRouteTypeForbidden %s", 403, payload)
}

func (o *RunsForRunAndRouteTypeForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RunsForRunAndRouteTypeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
