// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3BulkDeparturesStopResponse v3 bulk departures stop response
//
// swagger:model V3.BulkDeparturesStopResponse
type V3BulkDeparturesStopResponse struct {

	// Stop identifier
	StopID int32 `json:"stop_id,omitempty"`

	// Landmark in proximity of stop
	StopLandmark string `json:"stop_landmark,omitempty"`

	// Geographic coordinate of latitude at stop
	StopLatitude float32 `json:"stop_latitude,omitempty"`

	// Geographic coordinate of longitude at stop
	StopLongitude float32 `json:"stop_longitude,omitempty"`

	// Name of stop
	StopName string `json:"stop_name,omitempty"`

	// suburb of stop
	StopSuburb string `json:"stop_suburb,omitempty"`
}

// Validate validates this v3 bulk departures stop response
func (m *V3BulkDeparturesStopResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 bulk departures stop response based on context it is used
func (m *V3BulkDeparturesStopResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3BulkDeparturesStopResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3BulkDeparturesStopResponse) UnmarshalBinary(b []byte) error {
	var res V3BulkDeparturesStopResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
