// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3CacheKeyRemoved v3 cache key removed
//
// swagger:model V3.CacheKeyRemoved
type V3CacheKeyRemoved struct {

	// removed
	Removed bool `json:"Removed,omitempty"`
}

// Validate validates this v3 cache key removed
func (m *V3CacheKeyRemoved) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 cache key removed based on context it is used
func (m *V3CacheKeyRemoved) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3CacheKeyRemoved) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3CacheKeyRemoved) UnmarshalBinary(b []byte) error {
	var res V3CacheKeyRemoved
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
