// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3CacheItem v3 cache item
//
// swagger:model V3.CacheItem
type V3CacheItem struct {

	// type
	Type string `json:"Type,omitempty"`

	// value
	Value interface{} `json:"Value,omitempty"`
}

// Validate validates this v3 cache item
func (m *V3CacheItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 cache item based on context it is used
func (m *V3CacheItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3CacheItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3CacheItem) UnmarshalBinary(b []byte) error {
	var res V3CacheItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
