// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3InterchangeRoute Information about route interchange
//
// swagger:model V3.InterchangeRoute
type V3InterchangeRoute struct {

	// Indicates whether the interchange information is shown to end users
	Advertised bool `json:"advertised,omitempty"`

	// Route identifier
	RouteID int32 `json:"route_id,omitempty"`
}

// Validate validates this v3 interchange route
func (m *V3InterchangeRoute) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 interchange route based on context it is used
func (m *V3InterchangeRoute) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3InterchangeRoute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3InterchangeRoute) UnmarshalBinary(b []byte) error {
	var res V3InterchangeRoute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
