// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3JourneyLegPathCoordinate v3 journey leg path coordinate
//
// swagger:model V3.JourneyLegPathCoordinate
type V3JourneyLegPathCoordinate struct {

	// lat
	Lat float32 `json:"Lat,omitempty"`

	// lon
	Lon float32 `json:"Lon,omitempty"`
}

// Validate validates this v3 journey leg path coordinate
func (m *V3JourneyLegPathCoordinate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 journey leg path coordinate based on context it is used
func (m *V3JourneyLegPathCoordinate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3JourneyLegPathCoordinate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3JourneyLegPathCoordinate) UnmarshalBinary(b []byte) error {
	var res V3JourneyLegPathCoordinate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
