// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3OperatorsSocialFeedsResponse v3 operators social feeds response
//
// swagger:model V3.OperatorsSocialFeedsResponse
type V3OperatorsSocialFeedsResponse struct {

	// operators
	Operators *V3OperatorsSocialMediaModes `json:"operators,omitempty"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`
}

// Validate validates this v3 operators social feeds response
func (m *V3OperatorsSocialFeedsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperators(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3OperatorsSocialFeedsResponse) validateOperators(formats strfmt.Registry) error {
	if swag.IsZero(m.Operators) { // not required
		return nil
	}

	if m.Operators != nil {
		if err := m.Operators.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("operators")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("operators")
			}
			return err
		}
	}

	return nil
}

func (m *V3OperatorsSocialFeedsResponse) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v3 operators social feeds response based on the context it is used
func (m *V3OperatorsSocialFeedsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOperators(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3OperatorsSocialFeedsResponse) contextValidateOperators(ctx context.Context, formats strfmt.Registry) error {

	if m.Operators != nil {

		if swag.IsZero(m.Operators) { // not required
			return nil
		}

		if err := m.Operators.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("operators")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("operators")
			}
			return err
		}
	}

	return nil
}

func (m *V3OperatorsSocialFeedsResponse) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3OperatorsSocialFeedsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OperatorsSocialFeedsResponse) UnmarshalBinary(b []byte) error {
	var res V3OperatorsSocialFeedsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
