// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3OperatorSocialMediaAccount v3 operator social media account
//
// swagger:model V3.OperatorSocialMediaAccount
type V3OperatorSocialMediaAccount struct {

	// account name
	AccountName string `json:"account_name,omitempty"`

	// i o s url
	IOSURL string `json:"iOS_url,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this v3 operator social media account
func (m *V3OperatorSocialMediaAccount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 operator social media account based on context it is used
func (m *V3OperatorSocialMediaAccount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3OperatorSocialMediaAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OperatorSocialMediaAccount) UnmarshalBinary(b []byte) error {
	var res V3OperatorSocialMediaAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
