// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3PatternsParameters v3 patterns parameters
//
// swagger:model V3.PatternsParameters
type V3PatternsParameters struct {

	// Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)
	// Format: date-time
	DateUtc strfmt.DateTime `json:"date_utc,omitempty"`

	// List of objects to be returned in full (i.e. expanded) - options include: All, Stop, Route, Run, Direction, Disruption, VehiclePosition, VehicleDescriptor and None. Default is Disruption. Run must be expanded to receive VehiclePosition and VehicleDescriptor information.
	Expand []int32 `json:"expand"`

	// Indicates whether data related to interchanges should be included in the response (default = false)
	// When set to true, this parameter enables API clients to retrieve additional exchange information (stops, routes, runs, directions and disruptions) in a single call instead of making multiple requests
	IncludeAdvertisedInterchange bool `json:"include_advertised_interchange,omitempty"`

	// Indicates if geopath data will be returned (default = false)
	IncludeGeopath bool `json:"include_geopath,omitempty"`

	// Include any skipped stops in a stopping pattern. Defaults to false.
	IncludeSkippedStops bool `json:"include_skipped_stops,omitempty"`

	// Filter by stop_id; values returned by Stops API
	StopID int32 `json:"stop_id,omitempty"`
}

// Validate validates this v3 patterns parameters
func (m *V3PatternsParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateUtc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpand(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3PatternsParameters) validateDateUtc(formats strfmt.Registry) error {
	if swag.IsZero(m.DateUtc) { // not required
		return nil
	}

	if err := validate.FormatOf("date_utc", "body", "date-time", m.DateUtc.String(), formats); err != nil {
		return err
	}

	return nil
}

var v3PatternsParametersExpandItemsEnum []interface{}

func init() {
	var res []int32
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5,6,7,2147483647]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v3PatternsParametersExpandItemsEnum = append(v3PatternsParametersExpandItemsEnum, v)
	}
}

func (m *V3PatternsParameters) validateExpandItemsEnum(path, location string, value int32) error {
	if err := validate.EnumCase(path, location, value, v3PatternsParametersExpandItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V3PatternsParameters) validateExpand(formats strfmt.Registry) error {
	if swag.IsZero(m.Expand) { // not required
		return nil
	}

	for i := 0; i < len(m.Expand); i++ {

		// value enum
		if err := m.validateExpandItemsEnum("expand"+"."+strconv.Itoa(i), "body", m.Expand[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this v3 patterns parameters based on context it is used
func (m *V3PatternsParameters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3PatternsParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3PatternsParameters) UnmarshalBinary(b []byte) error {
	var res V3PatternsParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
