// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3RunAndRouteTypeParameters v3 run and route type parameters
//
// swagger:model V3.RunAndRouteTypeParameters
type V3RunAndRouteTypeParameters struct {

	// Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)
	// Format: date-time
	DateUtc strfmt.DateTime `json:"date_utc,omitempty"`

	// List of objects to be returned in full (i.e. expanded) - options include: All, VehiclePosition, VehicleDescriptor, or None. Default is None.
	Expand []int32 `json:"expand"`

	// Indicates if geopath data will be returned (default = false)
	IncludeGeopath bool `json:"include_geopath,omitempty"`
}

// Validate validates this v3 run and route type parameters
func (m *V3RunAndRouteTypeParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateUtc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpand(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3RunAndRouteTypeParameters) validateDateUtc(formats strfmt.Registry) error {
	if swag.IsZero(m.DateUtc) { // not required
		return nil
	}

	if err := validate.FormatOf("date_utc", "body", "date-time", m.DateUtc.String(), formats); err != nil {
		return err
	}

	return nil
}

var v3RunAndRouteTypeParametersExpandItemsEnum []interface{}

func init() {
	var res []int32
	if err := json.Unmarshal([]byte(`[0,1,2,2147483647]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v3RunAndRouteTypeParametersExpandItemsEnum = append(v3RunAndRouteTypeParametersExpandItemsEnum, v)
	}
}

func (m *V3RunAndRouteTypeParameters) validateExpandItemsEnum(path, location string, value int32) error {
	if err := validate.EnumCase(path, location, value, v3RunAndRouteTypeParametersExpandItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V3RunAndRouteTypeParameters) validateExpand(formats strfmt.Registry) error {
	if swag.IsZero(m.Expand) { // not required
		return nil
	}

	for i := 0; i < len(m.Expand); i++ {

		// value enum
		if err := m.validateExpandItemsEnum("expand"+"."+strconv.Itoa(i), "body", m.Expand[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this v3 run and route type parameters based on context it is used
func (m *V3RunAndRouteTypeParameters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3RunAndRouteTypeParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3RunAndRouteTypeParameters) UnmarshalBinary(b []byte) error {
	var res V3RunAndRouteTypeParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
