// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3SiriLineRef v3 siri line ref
//
// swagger:model V3.SiriLineRef
type V3SiriLineRef struct {

	// Siri DirectionRef  (in, out, up, down, clockwise, counterclockwise, Inbound, Outbound)
	// Enum: [1,2,5,10,16,32,65,130]
	DirectionRef int32 `json:"direction_ref,omitempty"`

	// Siri LineRef
	// Required: true
	LineRef *string `json:"line_ref"`
}

// Validate validates this v3 siri line ref
func (m *V3SiriLineRef) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectionRef(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLineRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var v3SiriLineRefTypeDirectionRefPropEnum []interface{}

func init() {
	var res []int32
	if err := json.Unmarshal([]byte(`[1,2,5,10,16,32,65,130]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v3SiriLineRefTypeDirectionRefPropEnum = append(v3SiriLineRefTypeDirectionRefPropEnum, v)
	}
}

// prop value enum
func (m *V3SiriLineRef) validateDirectionRefEnum(path, location string, value int32) error {
	if err := validate.EnumCase(path, location, value, v3SiriLineRefTypeDirectionRefPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *V3SiriLineRef) validateDirectionRef(formats strfmt.Registry) error {
	if swag.IsZero(m.DirectionRef) { // not required
		return nil
	}

	// value enum
	if err := m.validateDirectionRefEnum("direction_ref", "body", m.DirectionRef); err != nil {
		return err
	}

	return nil
}

func (m *V3SiriLineRef) validateLineRef(formats strfmt.Registry) error {

	if err := validate.Required("line_ref", "body", m.LineRef); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v3 siri line ref based on context it is used
func (m *V3SiriLineRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3SiriLineRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SiriLineRef) UnmarshalBinary(b []byte) error {
	var res V3SiriLineRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
