// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3SiriLineRefDirectionRefsDictionary v3 siri line ref direction refs dictionary
//
// swagger:model V3.SiriLineRefDirectionRefsDictionary
type V3SiriLineRefDirectionRefsDictionary struct {

	// direction refs
	DirectionRefs map[string][]V3SiriReferenceDataDetail `json:"direction_refs,omitempty"`

	// unmatched direction refs
	UnmatchedDirectionRefs map[string]string `json:"unmatched_direction_refs,omitempty"`
}

// Validate validates this v3 siri line ref direction refs dictionary
func (m *V3SiriLineRefDirectionRefsDictionary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectionRefs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriLineRefDirectionRefsDictionary) validateDirectionRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.DirectionRefs) { // not required
		return nil
	}

	for k := range m.DirectionRefs {

		if err := validate.Required("direction_refs"+"."+k, "body", m.DirectionRefs[k]); err != nil {
			return err
		}

		for i := 0; i < len(m.DirectionRefs[k]); i++ {

			if err := m.DirectionRefs[k][i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("direction_refs" + "." + k + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("direction_refs" + "." + k + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// ContextValidate validate this v3 siri line ref direction refs dictionary based on the context it is used
func (m *V3SiriLineRefDirectionRefsDictionary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirectionRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriLineRefDirectionRefsDictionary) contextValidateDirectionRefs(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.DirectionRefs {

		for i := 0; i < len(m.DirectionRefs[k]); i++ {

			if swag.IsZero(m.DirectionRefs[k][i]) { // not required
				return nil
			}

			if err := m.DirectionRefs[k][i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("direction_refs" + "." + k + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("direction_refs" + "." + k + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SiriLineRefDirectionRefsDictionary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SiriLineRefDirectionRefsDictionary) UnmarshalBinary(b []byte) error {
	var res V3SiriLineRefDirectionRefsDictionary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
