// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3SiriStopsRefsDictionary v3 siri stops refs dictionary
//
// swagger:model V3.SiriStopsRefsDictionary
type V3SiriStopsRefsDictionary struct {

	// stop point refs
	// Read Only: true
	StopPointRefs map[string]V3SiriReferenceDataDetail `json:"stop_point_refs,omitempty"`

	// unmatched stop point refs
	// Read Only: true
	UnmatchedStopPointRefs map[string]string `json:"unmatched_stop_point_refs,omitempty"`
}

// Validate validates this v3 siri stops refs dictionary
func (m *V3SiriStopsRefsDictionary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStopPointRefs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriStopsRefsDictionary) validateStopPointRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.StopPointRefs) { // not required
		return nil
	}

	for k := range m.StopPointRefs {

		if err := validate.Required("stop_point_refs"+"."+k, "body", m.StopPointRefs[k]); err != nil {
			return err
		}
		if val, ok := m.StopPointRefs[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stop_point_refs" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stop_point_refs" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v3 siri stops refs dictionary based on the context it is used
func (m *V3SiriStopsRefsDictionary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStopPointRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnmatchedStopPointRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriStopsRefsDictionary) contextValidateStopPointRefs(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.StopPointRefs {

		if val, ok := m.StopPointRefs[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *V3SiriStopsRefsDictionary) contextValidateUnmatchedStopPointRefs(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *V3SiriStopsRefsDictionary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SiriStopsRefsDictionary) UnmarshalBinary(b []byte) error {
	var res V3SiriStopsRefsDictionary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
