// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3StopBasic v3 stop basic
//
// swagger:model V3.StopBasic
type V3StopBasic struct {

	// stop id
	StopID int32 `json:"stop_id,omitempty"`

	// stop name
	StopName string `json:"stop_name,omitempty"`
}

// Validate validates this v3 stop basic
func (m *V3StopBasic) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 stop basic based on context it is used
func (m *V3StopBasic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3StopBasic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopBasic) UnmarshalBinary(b []byte) error {
	var res V3StopBasic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
