// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3SiriReferenceDataMappingsResponse v3 siri reference data mappings response
//
// swagger:model V3.SiriReferenceDataMappingsResponse
type V3SiriReferenceDataMappingsResponse struct {

	// SIRI LineRef
	// Read Only: true
	LineRefs map[string]V3SiriDirectionRefsDictionary `json:"line_refs,omitempty"`

	// mapping version
	// Read Only: true
	MappingVersion string `json:"mapping_version,omitempty"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`

	// stop point refs
	// Read Only: true
	StopPointRefs map[string]V3StopPoint `json:"stop_point_refs,omitempty"`
}

// Validate validates this v3 siri reference data mappings response
func (m *V3SiriReferenceDataMappingsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLineRefs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopPointRefs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) validateLineRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.LineRefs) { // not required
		return nil
	}

	for k := range m.LineRefs {

		if err := validate.Required("line_refs"+"."+k, "body", m.LineRefs[k]); err != nil {
			return err
		}
		if val, ok := m.LineRefs[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("line_refs" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("line_refs" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) validateStopPointRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.StopPointRefs) { // not required
		return nil
	}

	for k := range m.StopPointRefs {

		if err := validate.Required("stop_point_refs"+"."+k, "body", m.StopPointRefs[k]); err != nil {
			return err
		}
		if val, ok := m.StopPointRefs[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stop_point_refs" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stop_point_refs" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v3 siri reference data mappings response based on the context it is used
func (m *V3SiriReferenceDataMappingsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLineRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMappingVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStopPointRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) contextValidateLineRefs(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.LineRefs {

		if val, ok := m.LineRefs[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) contextValidateMappingVersion(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "mapping_version", "body", string(m.MappingVersion)); err != nil {
		return err
	}

	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V3SiriReferenceDataMappingsResponse) contextValidateStopPointRefs(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.StopPointRefs {

		if val, ok := m.StopPointRefs[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3SiriReferenceDataMappingsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SiriReferenceDataMappingsResponse) UnmarshalBinary(b []byte) error {
	var res V3SiriReferenceDataMappingsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
