// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3SiriDownstreamSubscriptionResponse v3 siri downstream subscription response
//
// swagger:model V3.SiriDownstreamSubscriptionResponse
type V3SiriDownstreamSubscriptionResponse struct {

	// The Data Horizon of Chronos
	// Format: date-time
	ValidUntil strfmt.DateTime `json:"valid_until,omitempty"`
}

// Validate validates this v3 siri downstream subscription response
func (m *V3SiriDownstreamSubscriptionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValidUntil(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3SiriDownstreamSubscriptionResponse) validateValidUntil(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidUntil) { // not required
		return nil
	}

	if err := validate.FormatOf("valid_until", "body", "date-time", m.ValidUntil.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v3 siri downstream subscription response based on context it is used
func (m *V3SiriDownstreamSubscriptionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3SiriDownstreamSubscriptionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3SiriDownstreamSubscriptionResponse) UnmarshalBinary(b []byte) error {
	var res V3SiriDownstreamSubscriptionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
