// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V3ZoneInfo v3 zone info
//
// swagger:model V3.ZoneInfo
type V3ZoneInfo struct {

	// max zone
	MaxZone int32 `json:"MaxZone,omitempty"`

	// min zone
	MinZone int32 `json:"MinZone,omitempty"`

	// unique zones
	UniqueZones []int32 `json:"UniqueZones"`
}

// Validate validates this v3 zone info
func (m *V3ZoneInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v3 zone info based on context it is used
func (m *V3ZoneInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3ZoneInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3ZoneInfo) UnmarshalBinary(b []byte) error {
	var res V3ZoneInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
